# Generated by Django 3.0.5 on 2021-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0002_maximum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maximum',
            name='max',
        ),
        migrations.AddField(
            model_name='maximum',
            name='confirmed',
            field=models.CharField(default='100', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maximum',
            name='date',
            field=models.CharField(default='100', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maximum',
            name='death',
            field=models.CharField(default='100', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maximum',
            name='discharged',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
