# Generated by Django 3.0.5 on 2021-01-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0003_auto_20210105_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='date',
            new_name='day',
        ),
    ]
