# Generated by Django 3.0.5 on 2021-01-06 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0004_auto_20210106_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
