# Generated by Django 3.0.5 on 2021-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0005_total_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='date',
        ),
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.DateField(),
        ),
    ]
