# Generated by Django 3.0.5 on 2021-01-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0007_remove_total_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='day',
            field=models.CharField(default='100', max_length=200),
            preserve_default=False,
        ),
    ]
