# Generated by Django 3.0.5 on 2021-01-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0010_auto_20210107_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.DateField(),
        ),
    ]
