# Generated by Django 3.0.5 on 2021-01-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0011_auto_20210107_0729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.CharField(max_length=200),
        ),
    ]
