# Generated by Django 3.0.5 on 2021-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0013_auto_20210107_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.CharField(max_length=200),
        ),
    ]
