# Generated by Django 3.0.5 on 2021-01-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0014_auto_20210107_1714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maximum',
        ),
    ]
