# Generated by Django 3.0.5 on 2021-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0015_delete_maximum'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
