# Generated by Django 3.0.5 on 2021-01-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0016_requestcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcount',
            name='total',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='total.Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
