# Generated by Django 3.0.5 on 2021-01-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0017_auto_20210111_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.DateTimeField(max_length=200),
        ),
    ]
