# Generated by Django 3.0.5 on 2021-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0018_auto_20210112_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.IntegerField(),
        ),
    ]
