# Generated by Django 3.0.5 on 2021-01-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0020_auto_20210112_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='RequestCount',
        ),
    ]
