# Generated by Django 3.0.5 on 2021-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0022_auto_20210112_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=1000)),
            ],
        ),
    ]
